apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: add-new-metric
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            customMetric: get_calls
          tagOverrides:
            upstream_proxy_version:
              operation: UPSERT
              value: "string(xds.node.metadata.ISTIO_VERSION)"
            source_mesh_id:
              operation: UPSERT
              value: "xds.node.metadata.MESH_ID"
