apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: istio-attributegen-filter
  namespace: istio-system
spec:
  url: https://storage.googleapis.com/istio-build/proxy/attributegen-359dcd3a19f109c50e97517fe6b1e2676e870c4d.wasm
  imagePullPolicy: Always
  phase: AUTHN
  pluginConfig:
    attributes:
      - output_attribute: "istio_operationId"
        match:
          - value: "getitems"
            condition: "request.url_path == '/items' && request.method == 'GET'"
          - value: "createitem"
            condition: "request.url_path == '/items' && request.method == 'POST'"
          - value: "deleteitem"
            condition: "request.url_path == '/items' && request.method == 'DELETE'"
