apiVersion: v1
data:
  setup.sh: |
    ls /
    echo "hello world!"
kind: ConfigMap
metadata:
  name: setup-script
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: pod-escape
  name: pod-escape
spec:
  selector:
    matchLabels:
      app: pod-escape
  template:
    metadata:
      labels:
        app: pod-escape
    spec:
      containers:
      - image: k8s.gcr.io/pause:3.1
        imagePullPolicy: IfNotPresent
        name: wait
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      initContainers:
      - args:
        - --mount=/proc/1/ns/mnt
        - --
        - sh
        - -c
        - $(SETUP_SCRIPT)
        command:
        - nsenter
        env:
        - name: SETUP_SCRIPT
          valueFrom:
            configMapKeyRef:
              key: setup.sh
              name: setup-script
        image: quay.io/bedrock/ubuntu
        imagePullPolicy: IfNotPresent
        name: init-node
        securityContext:
          privileged: true
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        operator: Exists
