crds:
  enabled: true


defaultRules:
  create: false
global:
  rbac:
    create: true
    createAggregateClusterRoles: false
    pspEnabled: false

prometheus-windows-exporter:
  prometheus:
    monitor:
      enabled: false
  releaseLabel: false

alertmanager:
  enabled: false

grafana:
  enabled: true
  adminUser: admin
  adminPassword: prom-operator
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true

      name: Prometheus
      uid: prometheus
      ## Set method for HTTP to send query to datasource
      httpMethod: POST

      prometheusServiceName: prometheus-operated
      label: grafana_datasource
      labelValue: "1"

      alertmanager:
        enabled: false

kubernetesServiceMonitors:
  enabled: true

kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false


prometheusOperator:
  enabled: true
  tls:
    enabled: false
  admissionWebhooks:
#    enabled: false

    patch:
      enabled: false

prometheus:
  service:
    nodePort: 30090
    type: ClusterIP
