apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 0.95
    failureLimit: 3 
    count: 5
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: | 
          sum(
            rate( 
              istio_requests_total{ 
                reporter="destination", 
                destination_workload_namespace=~"istioinaction", 
                destination_workload=~"canary", 
                response_code!~"5.*" 
              }[5m]
            )
          )
          /
          sum(
              rate(
                  istio_requests_total{
                    reporter="destination",
                    destination_workload_namespace=~"istioinaction",
                    destination_workload=~"canary",
                  }[5m]
              )
          )
