apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary
spec:
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: catalog
            routes:
            - catalog
          destinationRule:
            name: catalog
            canarySubsetName: canary 
            stableSubsetName: stable  
      steps:
        - setWeight: 10 # 새 버전을 10퍼센트로 맞춘다.
        - pause:
            duration: 30s
        - setWeight: 20
        - pause: {}
        - analysis:
            templates:
            - templateName: success-rate
        - pause: {}
  replicas: 5
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
        version: v3
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SHOW_IMAGE
          value: "false"
        image: istioinaction/catalog:latest
        name: catalog
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      securityContext: {}
      serviceAccountName: catalog
