crds:
  enabled: true
defaultRules:
  create: false
global:
  rbac:
    create: true
    createAggregateClusterRoles: false
    pspEnabled: false

prometheus-windows-exporter:
  prometheus:
    monitor:
      enabled: false
  releaseLabel: false

alertmanager:
  enabled: false

grafana:
  enabled: false

kubernetesServiceMonitors:
  enabled: true

kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false

prometheusOperator:
  enabled: true
  tls:
    enabled: false
  admissionWebhooks:
    patch:
      enabled: false

prometheus:
  service:
    type: ClusterIP
