# use user sam
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sam-secret
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sam-secret
  namespace: default
subjects:
  - kind: User
    name: sam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sam-secret
  apiGroup: rbac.authorization.k8s.io