apiVersion: v1
kind: Service
metadata:
  labels:
    app: headerer
  name: headerer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: headerer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: headerer
    version: v1
  name: headerer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headerer
      version: v1
  template:
    metadata:
      labels:
        app: headerer
        version: v1
    spec:
      containers:
      - image: zerotay/simple-headerer:0.1.0
        imagePullPolicy: IfNotPresent
        name: headerer
        env:
          - name: PORT
            value: "8080"
          - name: DEBUG
            value: "false"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false